entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSetup.java, entity-services/src/test/resources/entity-type-units/et-required.json, entity-services/src/test/resources/invalid-entity-types/invalid-bad-property.json
This is a pretty straightforward PR to fix a bug in schematron context.
=> bug:38858 validation of primaryKey in wrong place (JSON)

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsPayloadFunctions.java, entity-services-functionaltests/src/test/resources/invalid-entity-types/bug38858.json, entity-services-functionaltests/src/test/resources/test-database-properties/content-database.json, entity-services-functionaltests/src/test/resources/test-database-properties/content-database2.json, entity-services-functionaltests/src/test/resources/test-database-properties/content-database3.json
=> Some bug verification 

entity-services-examples/data/entity-types/simple-race-0.0.2.json, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/ExamplesBase.java, entity-services-examples/src/main/ml-config/databases/content-database.json, entity-services-examples/src/main/ml-modules/ext/Race-0.0.1.xqy, entity-services-examples/src/main/ml-modules/options/simple-race-gen.xml, entity-services-examples/src/main/ml-schemas/Race-0.0.1.tdex, entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy, entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/main/xdmp/entity-services/entity-services.xqy, entity-services/src/test/java/com/marklogic/entityservices/tests/TestRequired.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSearchOptions.java, entity-services/src/test/resources/entity-type-units/conversion-module.xqy, entity-services/src/test/resources/expected-search-options/SchemaCompleteEntityType-0.0.1.xml
This PR delivers search-options-generate.  The spec has been updated as well, and a few changes to examples are in a separate commit as I was doing PoC on the search options.
=> Search Options

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java, entity-services-functionaltests/src/test/resources/test-extract-instance/instance-Customer2.json, entity-services-functionaltests/src/test/resources/test-extract-instance/instance-Product2.json, entity-services-functionaltests/src/test/resources/test-extract-instance/instance-SchemaCompleteEntityType.json
bug#39655 : Required handling in conversion module
@grechaw @bsrikan  Charles please merge these testcases to develop so that Srikanth can pickmy changes and then add more test cases for other APIs like required handling in extraction-template-generate
=> Adding testcases for verifying bug#39655

entity-services-functionaltests/src/test/resources/entity-type-units/database-properties.json, entity-services-functionaltests/src/test/resources/test-database-properties/content-database.json, entity-services-functionaltests/src/test/resources/test-database-properties/content-database2.json, entity-services-functionaltests/src/test/resources/test-database-properties/content-database3.json
Required handling in database properties generate () API
@grechaw @bsrikan  Charles please merge these key changes to develop so that regression is cleaner tomorrow. I changed the key files for TestEsRequired.java and TestEsDatabaseProperties.java functional tests.
=> Changing the test key files to absorb change in DBpropgen() API

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java, entity-services-functionaltests/src/test/resources/test-search-options/valid-db-prop-et.xml
the keys are expected to be changed next week as few bugs in search
options generate are fixed and have gone into svn by end of today.
=> Adding a test for valid-db-prop-et.json model in TestSearchOptions.java

entity-services-examples/src/main/java/com/marklogic/entityservices/examples/CSVLoader.java, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/ExamplesBase.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsExtractionTemplates.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsRequired.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSchemaGeneration.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestSetup.java, entity-services/src/test/java/com/marklogic/entityservices/tests/EntityServicesTestBase.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestConversionModuleGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestDatabaseProperties.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypeSPARQL.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestExtractionTemplates.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestRequired.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSchemaGeneration.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSearchOptions.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSetup.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestTestInstanceGenerator.java
This PR has no functional changes, but it avoids loading unused data for each test, and so speeds things up considerably.
=> Improved testing performance and stylistic updates

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsDatabaseProperties.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsExtractionTemplates.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsInstanceGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSchemaGeneration.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java, entity-services-functionaltests/src/test/resources/test-extraction-template/SchemaCompleteEntityType-0.0.1.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-datatype-array.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-datatype-unsignedInt.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-no-baseUri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-northwind1.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-properties-empty.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-range-index.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-combo-sameDocument-subIri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-same-document.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-subject-uri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-value-as-nonString.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref.xml
@grechaw This PR contains test and key updates for bug 38517 and bug 40472.
@rashiatmarklogic You can add your commit hash in the comment here and Charles can select/include them to be merged to develop. As discussed you might have changes to same class files but I have added new tests so I wouldnt expect any merge conflict.
=> test and key updates for bug fixes

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSchemaGeneration.java
@grechaw 
This PR includes updates to schema generation test to include ET docs that work OK without any validatebadschema error. Also added logic to include validation of all the test instances than just the ones ending with -0.xml
=> Updated schema generation test

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java, entity-services-functionaltests/src/test/resources/test-search-options/valid-no-baseUri.xml
identified with this addition.
@bsrikan @grechaw : does not add a lot of value to testing search-options-generate() but since I checked this model, m creating this PR.
=> Adding another model for search-options-generate() API. No bug

entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy, entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/main/xdmp/entity-services/entity-services.xqy, entity-services/src/test/java/com/marklogic/entityservices/tests/TestVersionComparison.java, entity-services/src/test/resources/entity-type-units/conversion-module.xqy, entity-services/src/test/resources/entity-type-units/conversion-source.json, entity-services/src/test/resources/entity-type-units/conversion-target.json, entity-services/src/test/resources/entity-type-units/instance-0.0.1.xml
includes fix to bug:40662, comment about array to scalar
This is not a complete delivery of the version-comparison but it is well enough along to build, generate code, run functions, and seems to do the right thing sometimes.
=> Version comparison, bug:36574

entity-services-functionaltests/src/test/resources/entity-type-units/conversion-module.xqy
@grechaw : Please merge this PR , testEsRequired will still fail 07/19 but because of 40666.
=> Bug 40664 changing the keys because of this bug.

entity-services-functionaltests/src/test/resources/entity-type-units/conversion-module.xqy, entity-services-functionaltests/src/test/resources/entity-type-units/schema.xml
@grechaw 
Can you please merge this key update today. This PR includes key updates TestRequired.
@rashiatmarklogic 
Thanks,
Srikanth
=> bug:40664,bug:40766 Updated keys for TestRequired

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsPayloadFunctions.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsRequired.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSchemaGeneration.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsVersionTranslatorGenerate.java, entity-services-functionaltests/src/test/resources/entity-type-units/conversion-module.xqy, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-bad-datatype.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-baseUri-colon.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-datatype-ref-together.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-definitions-empty.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-info-notobject.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-datatype.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-definitions.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-info.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-items-when-datatype-array.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-title.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-version.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-multiple-primarykey.xml, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-range-index.xml, entity-services-functionaltests/src/test/resources/test-version-translator/srcTgtSame.json
Updated payloadFunctions,Required,SchemaGeneration,SearchOptions,VersionTranslatorGenerate test and xml testdata files
@grechaw @rashiatmarklogic Please review and merge for a cleaner regression test.
=> bug:40836 test and testdata changes

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestSetup.java
http://marklogic.com/entity-services/entity-types to
http://marklogic.com/entity-services/models - This makes
TestEsEntityTypeSPARQL.java pass.
@bsrikan @grechaw 
Srikanth - Please go ahead and merge this change to develop branch, lets try this way before Charles leaves tomorrow. You should be able to merge it.
=> Changing the TDE collection from

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsExtractionTemplates.java, entity-services-functionaltests/src/test/resources/test-extraction-template/SchemaCompleteEntityType-0.0.1.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/SchemaCompleteEntityType-0.0.2.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/no-primary-required.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-datatype-array.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-datatype-unsignedInt.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-db-prop-et.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-no-baseUri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-northwind1.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-properties-empty.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-range-index.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-combo-sameDocument-subIri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-same-document.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-subject-uri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-value-as-nonString.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-simple-ref.xml
functional test. Uncommenting them and changing keys files after
verifying 39021 and 39013.
I am merging this PR since I am confident that the changes are all expected.
=> By mistake I had commented out all the tests in Extraction template

entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/main/xdmp/entity-services/entity-services.xqy, entity-services/src/test/java/com/marklogic/entityservices/tests/TestDatabaseProperties.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestExtractionTemplates.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestInstanceConverterGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestRequired.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSchemaGeneration.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSearchOptions.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestTestInstanceGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestVersionTranslator.java
Hi @bsrikan this PR has all the changes required to refactor the interface as described in recent emails.
I'll complete a spec update this afternoon.
=> Implements #101, design changes to validation

entity-services/src/test/java/com/marklogic/entityservices/tests/EntityServicesTestBase.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestDatabaseProperties.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestExtractionTemplates.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestInstanceConverterGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestRequired.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSchemaGeneration.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSearchOptions.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestTestInstanceGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestVersionTranslator.java
Looks clean to me, what you think @bsrikan ?
=> Test updates for refactoring function

entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/test/resources/model-units/et-required.json, entity-services/src/test/resources/model-units/extraction-template.xml, entity-services/src/test/resources/model-units/instance-converter.xqy
This is a simple fix to revert how graph iri worked before.  Will merge on your eyes @bsrikan
=> Issue  #145 fix graph iri regression

entity-services-examples/src/main/java/com/marklogic/entityservices/examples/race/ExamplesLoader.java, entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java
Hi @bsrikan this commit fixes the issue we see on Windows for loading invalid entity types.
=> Fix issue on windows for loading invalid types

entity-services-functionaltests/src/test/resources/entity-type-units/conversion-module.xqy, entity-services/src/test/resources/model-units/instance-converter.xqy
@grechaw This PR contains cosmetic key updates for #190.
=> Updated keys for Required in unit and functional tests

entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy
Hello @bsrikan @rashiatmarklogic , Here is a very small fix that addresses the lack of comparison for "None" in a target.  It's pretty straightforward.  OK to merge?
=> Issue #139 modification to report section

entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy
I think this commit covers the three points you've mentioned in your issue.  What do you think @bsrikan ?
=> Issue #220, comment fixes

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsVersionTranslatorGenerate.java, entity-services-functionaltests/src/test/resources/source-documents/northwind/customers/GODOS.xml, entity-services-functionaltests/src/test/resources/source-documents/northwind/customers/VINET.json, entity-services-functionaltests/src/test/resources/source-documents/northwind/products/51.xml, entity-services-functionaltests/src/test/resources/source-documents/northwind/products/72.xml, entity-services-functionaltests/src/test/resources/test-attachments/jsonAttachment.json, entity-services-functionaltests/src/test/resources/test-extract-instance/convert-instance-Product.json, entity-services-functionaltests/src/test/resources/test-extract-instance/instance-Customer2.json, entity-services-functionaltests/src/test/resources/test-extract-instance/instance-Order.json, entity-services-functionaltests/src/test/resources/test-version-translator/allDifferent.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/array2ScalarConv.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/localArrayRefs.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/newPKey.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/sameTgt-Src.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/sameTgt-Tgt.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/scalar2ArrayConv.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/srcHasAdditionalProp.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/srcHasETTgtDsnt.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/srcRefDiffDatatype.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/tgtHasAdditionalProp.xqy, entity-services-functionaltests/src/test/resources/test-version-translator/tgtHasETSrcDsnt.xqy, entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy
@grechaw This PR includes test/key updates for version translator comment fixes and new test for #207. Subscribing @rashiatmarklogic 
I also have a new test(testConvInst2) added for #221 in versionTranslator which I would like for you to have a closer look as I doubt "CustomerID" should return null.
Finally, I am not sure how I got your commits in my fork. Maybe when I was playing with "git rebase -i".
Thanks,
Srikanth
=> PR with tests and key updates for bug fixes

entity-services-examples/example-person/person-qc.xml, entity-services-examples/example-races/races-qc.xml, entity-services-examples/example-suppliers/suppliers-qc.xml, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/ExamplesBase.java, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/race/CSVLoader.java, entity-services-examples/src/main/resources/logback.xml
Had a JavaScript error in one of the tabs.
=> Person QC Update

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsExtractionTemplates.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsPayloadFunctions.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsVersionTranslatorGenerate.java, entity-services-functionaltests/src/test/resources/entity-type-units/extraction-template.xml, entity-services-functionaltests/src/test/resources/entity-type-units/test-envelope-no-instances.xml, entity-services-functionaltests/src/test/resources/entity-type-units/test-envelope-with-sequences.xml, entity-services-functionaltests/src/test/resources/json-entity-types/person.json, entity-services-functionaltests/src/test/resources/json-entity-types/valid-northwind1.json, entity-services-functionaltests/src/test/resources/test-extraction-template/SchemaCompleteEntityType-0.0.1.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/SchemaCompleteEntityType-0.0.2.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/no-primary-yes-required.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/person.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-datatype-array.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-datatype-unsignedInt.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-db-prop-et.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-no-baseUri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-northwind1.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-properties-empty.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-range-index.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-combo-sameDocument-subIri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-same-document.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-subject-uri.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref-value-as-nonString.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-ref.xml, entity-services-functionaltests/src/test/resources/test-extraction-template/valid-simple-ref.xml, entity-services-functionaltests/src/test/resources/test-search-options/valid-northwind1.xml, entity-services-functionaltests/src/test/resources/xml-entity-types/valid-northwind1.xml
This PR now includes updates to functional tests as a result of bugfixes PR from @grechaw.
FYI @rashiatmarklogic
=> PR with functionaltests for bugfixes pr and e2e updates

entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsPayloadFunctions.java, entity-services-functionaltests/src/test/resources/invalid-entity-types/invalid-missing-items-datatype.xml, entity-services-functionaltests/src/test/resources/test-instance-from-document/jsonEmptyArray.json, entity-services-functionaltests/src/test/resources/test-instance-from-document/jsonSerialization.json, entity-services-functionaltests/src/test/resources/test-instance-from-document/noRef-from-document.json, entity-services-functionaltests/src/test/resources/test-instance-from-document/noRef-json-from-document.json
@grechaw Please merge this PR to develop. It contains tests and updated keys for #264 and #270
=> QA PR for recent bug fixes

entity-services/src/test/java/com/marklogic/entityservices/tests/TestExtractionTemplates.java
This change to TDE tests uses a server eval to call tde:template-insert to create TDEs.  Since this operation validates TDE before inserting, I had to change where I did testing for validation (not insert invalid templates).
@bsrikan you may have similar issues in functional tests.
=> Issue with TDE tests #271

README.md, entity-services-examples/README.md, entity-services-examples/example-versions/README.md
Here is a lot more info to go into the versions README.  Please give it a read-over and see what you think.
=> Example-versions readme update Issue #262

build.gradle, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/EntityServicesTestBase.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsDatabaseProperties.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsEntityTypeSPARQL.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsExtractionTemplates.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsInstanceGenerator.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsPayloadFunctions.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsRequired.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSchemaGeneration.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsVersionTranslatorGenerate.java, entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestSetup.java, entity-services/src/test/java/com/marklogic/entityservices/tests/EntityServicesTestBase.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestDatabaseProperties.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypeSPARQL.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEvalException.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestExtractionTemplates.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestInstanceConverterGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestRequired.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSchemaGeneration.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSearchOptions.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSetup.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestTestInstanceGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestVersionTranslator.java, entity-services/src/test/resources/model-units/instance-converter.xqy, entity-services/src/test/resources/xml-models/SchemaCompleteEntityType-0.0.1.xml
Hi Srikanth, I'd like to discuss this PR with you.
I went about upgrading the XMLUnit 2.0 stuff, but see some things in the functional tests not passing, including what you reported in #303. 
If you could take a look at this and see what you think about incorporating, whether the remaining test adjustments are simple, etc.  I think it would be a good time to get the testing upgrade in place if we can.
=> Xmlunit2 upgrade

entity-services-examples/run-all.sh, entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy, entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/main/xdmp/entity-services/entity-services.ttl, entity-services/src/main/xdmp/entity-services/entity-services.xqy, entity-services/src/test/java/com/marklogic/entityservices/tests/TestEntityTypes.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestInstanceConverterGenerator.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestRequired.java, entity-services/src/test/java/com/marklogic/entityservices/tests/TestSearchOptions.java, entity-services/src/test/resources/expected-database-properties/content-database.json, entity-services/src/test/resources/expected-search-options/SchemaCompleteEntityType-0.0.1.xml, entity-services/src/test/resources/json-models/Person-0.0.2.json, entity-services/src/test/resources/json-models/SchemaCompleteEntityType-0.0.1.json, entity-services/src/test/resources/model-units/database-properties.json, entity-services/src/test/resources/model-units/instance-converter.xqy, entity-services/src/test/resources/test-instances/Person-0.0.2-0.xml, entity-services/src/test/resources/test-instances/SchemaCompleteEntityType-0.0.1-0.xml, entity-services/src/test/resources/test-instances/SchemaCompleteEntityType-0.0.1-1.xml, entity-services/src/test/resources/triples-expected/Person-0.0.2.ttl, entity-services/src/test/resources/triples-expected/SchemaCompleteEntityType-0.0.1.ttl, entity-services/src/test/resources/xml-models/Person-0.0.2.xml, entity-services/src/test/resources/xml-models/SchemaCompleteEntityType-0.0.1.xml
JSON envelopes #308
Aesthetic fixes in  #304
Also, #303 also is fixed in this commit
=> Issue #309, path and element ranges

build.gradle, entity-services-examples/build.gradle, entity-services-examples/example-els/Customer-pii-0.0.1.json, entity-services-examples/example-els/README.md, entity-services-examples/example-els/ml-config/databases/content-database.json, entity-services-examples/example-els/ml-config/databases/schemas-database.json, entity-services-examples/example-els/ml-config/security/roles/10-examples-reader.json, entity-services-examples/example-els/ml-config/security/roles/20-examples-writer.json, entity-services-examples/example-els/ml-config/security/roles/25-examples-admin.json, entity-services-examples/example-els/ml-config/security/roles/30-privileged-to-see-pii.json, entity-services-examples/example-els/ml-config/security/users/adminy-user.json, entity-services-examples/example-els/ml-config/security/users/non-privileged-user.json, entity-services-examples/example-els/ml-config/security/users/privileged-user.json, entity-services-examples/example-els/ml-config/security/users/writer-user.json, entity-services-examples/example-els/ml-modules/options/pii.xml, entity-services-examples/example-els/ml-modules/services/els-pii.xqy, entity-services-examples/example-els/ml-modules/transforms/ingest-customer.xqy, entity-services-examples/example-els/ml-modules/transforms/turtle-to-xml.xqy, entity-services-examples/example-els/ml-schemas/Secure-0.0.1.tdex, entity-services-examples/example-els/ml-schemas/Secure-0.0.1.xsd, entity-services-examples/example-els/pii-policy.ttl, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/ExamplesBase.java, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/els/Customer.java, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/els/ElementLevelSecurityExample.java, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/els/Queryer.java, entity-services-examples/src/main/java/com/marklogic/entityservices/examples/els/SecureCustomers.java, entity-services-examples/src/main/resources/logback.xml, entity-services-examples/src/main/resources/secured-app.properties, entity-services/src/test/java/com/marklogic/entityservices/tests/TestInstanceConverterGenerator.java
Hi @bsrikan , @jmakeig , this is the revised ELS example.
It needs review, perhaps edits, but I think it's pretty clean.
See if README makes sense, what more I can do to make this loverly.
=> Els recipe

entity-services-functionaltests/src/test/resources/test-search-options/SchemaCompleteEntityType-0.0.1.xml, entity-services-functionaltests/src/test/resources/test-search-options/invalid-primary-key-as-ref.xml, entity-services-functionaltests/src/test/resources/test-search-options/valid-1-namespace.xml, entity-services-functionaltests/src/test/resources/test-search-options/valid-2-namespace.xml, entity-services-functionaltests/src/test/resources/test-search-options/valid-db-prop-et.xml, entity-services-functionaltests/src/test/resources/test-search-options/valid-no-baseUri.xml, entity-services-functionaltests/src/test/resources/test-search-options/valid-northwind1.xml
Key updates to search options test.
@grechaw Please review and merge.
These changes needs to be pushed to develop as well.
=> Updated keys for search options test per changes to 9.0-5 bug:49264

entity-services-functionaltests/src/test/resources/test-pii-generate/els-config.json, entity-services/src/main/xdmp/entity-services/entity-services-impl.xqy, entity-services/src/test/resources/model-units/Customer-piiconfig.json, entity-services/src/test/resources/model-units/Order-piiconfig.json
Hi @bsrikan here are the tune-ups that ELS config needs for DHF.  Should be pretty easy to assimilate.
=> Els config tune
